name: Test security

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Send mail
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Github Actions - Mail recieved
          # Literal body:
          body: Build job of ${{github.repository}} completed successfully! My username is ${{secrets.MAIL_USERNAME}}.
          to: djl-dev@amazon.com
          from: Test Security PR
